salamon_covus_homepage:
    path:     /hello/{name}
    defaults: { _controller: SalamonCovusBundle:Default:index }

fos_user_registration_register:
    path:     /user/register/step1
    defaults: { _controller: SalamonCovusBundle:Registration:register }

fos_user_covus_setalltrue:
    path:     /user/set/alltrue
    defaults: { _controller: SalamonCovusBundle:Covus:setAllTrue }

fos_user_covus_edit:
    path:     /user/edit
    defaults: { _controller: SalamonCovusBundle:Covus:edit }
